In [4]:
import pandas as pd

In [5]:
data_jobfair = pd.read_excel('data_jobfair.xlsx')
data_jobfair

,_id,__v,address,createdAt,date_of_birth,deleted,gender,major,marital_status,physical_condition,profession,status_education,updatedAt,user_id,work_experience
0,6164d6a1c53d4900eb93ca7d,0,Kemuning II Nomor 1 Semarang,2021-10-12 00:28:17.103,1988-08-24,False,615e60a03c1e73007be5ccfc,Ilmu Kesejahteraan Sosial,61639bddf265eb00cf9687d1,615d586d1c31b1006dc95261,0,615d57951c31b1006dc9524d,2021-10-12 00:28:17.103,6164d6a0c53d4900eb93ca79,0
1,6167b48a36fd26a8968715cb,0,Jamprit RT 05 Panjangrejo Pundong Bantul Yogya...,2021-10-14 04:39:38.926,2021-10-14,False,615e60a03c1e73007be5ccfc,teknik,61639bddf265eb00cf9687d1,615d586d1c31b1006dc95261,menganggur,615d57831c31b1006dc95249,2021-10-14 04:39:38.926,6167b48a36fd26a8968715c7,tidak punya
2,616e0a3f0b9434a8f783a9c6,0,"SITISEWU GT.I/326, RT2, RW1, SOSROMENDURAN, GE...",2021-10-18 23:58:55.784,1996-06-23,False,615e60a03c1e73007be5ccfc,TEKNIK INFORMATIKA,61639bc1f265eb00cf9687c8,615d586d1c31b1006dc95261,fresh graduate,615d57831c31b1006dc95249,2021-10-18 23:58:55.784,616e0a3f0b9434a8f783a9c2,fresh graduate
3,61775332e8ae91003ce09423,0,"WIROBRAJAN WB 2/380 YOGYAKARTA, RT16, RW4, WIR...",2021-10-26 01:00:34.716,1999-08-27,False,615e60a03c1e73007be5ccfc,Teknik Multi Media,61639bc1f265eb00cf9687c8,615d586d1c31b1006dc95261,Pelajar,615d57461c31b1006dc9523d,2021-10-26 01:00:34.716,61775328125736004cceb9cb,Magang di Percetakan Duta Fokus
4,61775d18e8ae91003ce09aec,0,"JL.PANTI WREDHA PONGGALAN UH VII NO.164, RT14,...",2021-10-26 01:42:48.855,1981-09-04,False,615e60a03c1e73007be5ccfc,SISTEM INFORMASI,61639bddf265eb00cf9687d1,615d586d1c31b1006dc95261,Pelajar,615d57831c31b1006dc95249,2021-10-26 01:42:48.855,61775d1817c4e8004c70e2f4,Tidak ada
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1604,6505945b5554a70006e49c7c,0,"Perum. Candi Indah M-12, RT 28, RW 72, Jetis, ...",2023-09-16 11:41:15.121,1998-01-01,False,615e60a03c1e73007be5ccfc,Apoteker,61639bc1f265eb00cf9687c8,615d586d1c31b1006dc95261,Fresh Graduate,615d57831c31b1006dc95249,2023-09-16 11:41:15.121,6505945a5554a70006e49c79,Praktik di Industri PT. Nufarindo (Production ...
1605,650db94bd3187e0007b02801,0,"JL IREDA 105 YOGYAKARTA, RT 44 RW 10, KEPARAKA...",2023-09-22 15:56:59.704,1988-06-09,False,615e60a03c1e73007be5ccfc,IPA,61639bc1f265eb00cf9687c8,615d586d1c31b1006dc95261,Cook,615d57461c31b1006dc9523d,2023-09-22 15:56:59.704,650db94bd3187e0007b027fe,Cook
1606,65137138337a44000661ba61,0,"Gg.ISMOYO 6 SINGOSAREN KIDUL., RT 4 RW 1, WIRO...",2023-09-27 00:03:04.233,1998-02-09,False,615e60a03c1e73007be5ccfc,Akuntansi,61639bc1f265eb00cf9687c8,615d586d1c31b1006dc95261,Freshgraduate,615d57831c31b1006dc95249,2023-09-27 00:03:04.233,65137138337a44000661ba5e,Drafter - CV. Karya Hidup Sentosa (2016-2019)
1607,651d0171bfc23d0007915624,0,"Tambaksari, Blora",2023-10-04 06:08:49.721,1998-01-16,False,615e60b53c1e73007be5cd01,agribisnis,61639bc1f265eb00cf9687c8,615d58571c31b1006dc9525d,telemarketer,615d57831c31b1006dc95249,2023-10-04 06:08:49.721,651d0171bfc23d0007915621,pengalaman kerja menjadi agent telemarketer di...
1608,651d3ae3bfc23d00079159de,0,"JL.JOGOKARIYAN NO.43 A, RT 46 RW 12, MANTRIJER...",2023-10-04 10:13:55.952,1981-04-10,False,615e60a03c1e73007be5ccfc,Akuntansi,61639bc1f265eb00cf9687c8,615d586d1c31b1006dc95261,22 Agustus 2022,615d57461c31b1006dc9523d,2023-10-04 10:13:55.952,651d3ae3bfc23d00079159db,Pernah di gudang expedisi

In [6]:
data_jobfair.isna().sum()

# Langkah 1: Hapus baris dengan data kosong di kolom "Date of Birth"
data_jobfair = data_jobfair.dropna(subset=["date_of_birth"])

# Langkah 2: Ganti data kosong di kolom lain dengan "-"
data_jobfair= data_jobfair.fillna("-")
data_jobfair

,_id,__v,address,createdAt,date_of_birth,deleted,gender,major,marital_status,physical_condition,profession,status_education,updatedAt,user_id,work_experience
0,6164d6a1c53d4900eb93ca7d,0,Kemuning II Nomor 1 Semarang,2021-10-12 00:28:17.103,1988-08-24,False,615e60a03c1e73007be5ccfc,Ilmu Kesejahteraan Sosial,61639bddf265eb00cf9687d1,615d586d1c31b1006dc95261,0,615d57951c31b1006dc9524d,2021-10-12 00:28:17.103,6164d6a0c53d4900eb93ca79,0
1,6167b48a36fd26a8968715cb,0,Jamprit RT 05 Panjangrejo Pundong Bantul Yogya...,2021-10-14 04:39:38.926,2021-10-14,False,615e60a03c1e73007be5ccfc,teknik,61639bddf265eb00cf9687d1,615d586d1c31b1006dc95261,menganggur,615d57831c31b1006dc95249,2021-10-14 04:39:38.926,6167b48a36fd26a8968715c7,tidak punya
2,616e0a3f0b9434a8f783a9c6,0,"SITISEWU GT.I/326, RT2, RW1, SOSROMENDURAN, GE...",2021-10-18 23:58:55.784,1996-06-23,False,615e60a03c1e73007be5ccfc,TEKNIK INFORMATIKA,61639bc1f265eb00cf9687c8,615d586d1c31b1006dc95261,fresh graduate,615d57831c31b1006dc95249,2021-10-18 23:58:55.784,616e0a3f0b9434a8f783a9c2,fresh graduate
3,61775332e8ae91003ce09423,0,"WIROBRAJAN WB 2/380 YOGYAKARTA, RT16, RW4, WIR...",2021-10-26 01:00:34.716,1999-08-27,False,615e60a03c1e73007be5ccfc,Teknik Multi Media,61639bc1f265eb00cf9687c8,615d586d1c31b1006dc95261,Pelajar,615d57461c31b1006dc9523d,2021-10-26 01:00:34.716,61775328125736004cceb9cb,Magang di Percetakan Duta Fokus
4,61775d18e8ae91003ce09aec,0,"JL.PANTI WREDHA PONGGALAN UH VII NO.164, RT14,...",2021-10-26 01:42:48.855,1981-09-04,False,615e60a03c1e73007be5ccfc,SISTEM INFORMASI,61639bddf265eb00cf9687d1,615d586d1c31b1006dc95261,Pelajar,615d57831c31b1006dc95249,2021-10-26 01:42:48.855,61775d1817c4e8004c70e2f4,Tidak ada
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1604,6505945b5554a70006e49c7c,0,"Perum. Candi Indah M-12, RT 28, RW 72, Jetis, ...",2023-09-16 11:41:15.121,1998-01-01,False,615e60a03c1e73007be5ccfc,Apoteker,61639bc1f265eb00cf9687c8,615d586d1c31b1006dc95261,Fresh Graduate,615d57831c31b1006dc95249,2023-09-16 11:41:15.121,6505945a5554a70006e49c79,Praktik di Industri PT. Nufarindo (Production ...
1605,650db94bd3187e0007b02801,0,"JL IREDA 105 YOGYAKARTA, RT 44 RW 10, KEPARAKA...",2023-09-22 15:56:59.704,1988-06-09,False,615e60a03c1e73007be5ccfc,IPA,61639bc1f265eb00cf9687c8,615d586d1c31b1006dc95261,Cook,615d57461c31b1006dc9523d,2023-09-22 15:56:59.704,650db94bd3187e0007b027fe,Cook
1606,65137138337a44000661ba61,0,"Gg.ISMOYO 6 SINGOSAREN KIDUL., RT 4 RW 1, WIRO...",2023-09-27 00:03:04.233,1998-02-09,False,615e60a03c1e73007be5ccfc,Akuntansi,61639bc1f265eb00cf9687c8,615d586d1c31b1006dc95261,Freshgraduate,615d57831c31b1006dc95249,2023-09-27 00:03:04.233,65137138337a44000661ba5e,Drafter - CV. Karya Hidup Sentosa (2016-2019)
1607,651d0171bfc23d0007915624,0,"Tambaksari, Blora",2023-10-04 06:08:49.721,1998-01-16,False,615e60b53c1e73007be5cd01,agribisnis,61639bc1f265eb00cf9687c8,615d58571c31b1006dc9525d,telemarketer,615d57831c31b1006dc95249,2023-10-04 06:08:49.721,651d0171bfc23d0007915621,pengalaman kerja menjadi agent telemarketer di...
1608,651d3ae3bfc23d00079159de,0,"JL.JOGOKARIYAN NO.43 A, RT 46 RW 12, MANTRIJER...",2023-10-04 10:13:55.952,1981-04-10,False,615e60a03c1e73007be5ccfc,Akuntansi,61639bc1f265eb00cf9687c8,615d586d1c31b1006dc95261,22 Agustus 2022,615d57461c31b1006dc9523d,2023-10-04 10:13:55.952,651d3ae3bfc23d00079159db,Pernah di gudang expedisi

Usia saat melamar kerja

In [7]:
data_jobfair['usia_saat_melamar'] = (pd.to_datetime(data_jobfair['updatedAt']) - pd.to_datetime(data_jobfair['date_of_birth'])).astype('<m8[Y]')
data_jobfair

,_id,__v,address,createdAt,date_of_birth,deleted,gender,major,marital_status,physical_condition,profession,status_education,updatedAt,user_id,work_experience,usia_saat_melamar
0,6164d6a1c53d4900eb93ca7d,0,Kemuning II Nomor 1 Semarang,2021-10-12 00:28:17.103,1988-08-24,False,615e60a03c1e73007be5ccfc,Ilmu Kesejahteraan Sosial,61639bddf265eb00cf9687d1,615d586d1c31b1006dc95261,0,615d57951c31b1006dc9524d,2021-10-12 00:28:17.103,6164d6a0c53d4900eb93ca79,0,33.0
1,6167b48a36fd26a8968715cb,0,Jamprit RT 05 Panjangrejo Pundong Bantul Yogya...,2021-10-14 04:39:38.926,2021-10-14,False,615e60a03c1e73007be5ccfc,teknik,61639bddf265eb00cf9687d1,615d586d1c31b1006dc95261,menganggur,615d57831c31b1006dc95249,2021-10-14 04:39:38.926,6167b48a36fd26a8968715c7,tidak punya,0.0
2,616e0a3f0b9434a8f783a9c6,0,"SITISEWU GT.I/326, RT2, RW1, SOSROMENDURAN, GE...",2021-10-18 23:58:55.784,1996-06-23,False,615e60a03c1e73007be5ccfc,TEKNIK INFORMATIKA,61639bc1f265eb00cf9687c8,615d586d1c31b1006dc95261,fresh graduate,615d57831c31b1006dc95249,2021-10-18 23:58:55.784,616e0a3f0b9434a8f783a9c2,fresh graduate,25.0
3,61775332e8ae91003ce09423,0,"WIROBRAJAN WB 2/380 YOGYAKARTA, RT16, RW4, WIR...",2021-10-26 01:00:34.716,1999-08-27,False,615e60a03c1e73007be5ccfc,Teknik Multi Media,61639bc1f265eb00cf9687c8,615d586d1c31b1006dc95261,Pelajar,615d57461c31b1006dc9523d,2021-10-26 01:00:34.716,61775328125736004cceb9cb,Magang di Percetakan Duta Fokus,22.0
4,61775d18e8ae91003ce09aec,0,"JL.PANTI WREDHA PONGGALAN UH VII NO.164, RT14,...",2021-10-26 01:42:48.855,1981-09-04,False,615e60a03c1e73007be5ccfc,SISTEM INFORMASI,61639bddf265eb00cf9687d1,615d586d1c31b1006dc95261,Pelajar,615d57831c31b1006dc95249,2021-10-26 01:42:48.855,61775d1817c4e8004c70e2f4,Tidak ada,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1604,6505945b5554a70006e49c7c,0,"Perum. Candi Indah M-12, RT 28, RW 72, Jetis, ...",2023-09-16 11:41:15.121,1998-01-01,False,615e60a03c1e73007be5ccfc,Apoteker,61639bc1f265eb00cf9687c8,615d586d1c31b1006dc95261,Fresh Graduate,615d57831c31b1006dc95249,2023-09-16 11:41:15.121,6505945a5554a70006e49c79,Praktik di Industri PT. Nufarindo (Production ...,25.0
1605,650db94bd3187e0007b02801,0,"JL IREDA 105 YOGYAKARTA, RT 44 RW 10, KEPARAKA...",2023-09-22 15:56:59.704,1988-06-09,False,615e60a03c1e73007be5ccfc,IPA,61639bc1f265eb00cf9687c8,615d586d1c31b1006dc95261,Cook,615d57461c31b1006dc9523d,2023-09-22 15:56:59.704,650db94bd3187e0007b027fe,Cook,35.0
1606,65137138337a44000661ba61,0,"Gg.ISMOYO 6 SINGOSAREN KIDUL., RT 4 RW 1, WIRO...",2023-09-27 00:03:04.233,1998-02-09,False,615e60a03c1e73007be5ccfc,Akuntansi,61639bc1f265eb00cf9687c8,615d586d1c31b1006dc95261,Freshgraduate,615d57831c31b1006dc95249,2023-09-27 00:03:04.233,65137138337a44000661ba5e,Drafter - CV. Karya Hidup Sentosa (2016-2019),25.0
1607,651d0171bfc23d0007915624,0,"Tambaksari, Blora",2023-10-04 06:08:49.721,1998-01-16,False,615e60b53c1e73007be5cd01,agribisnis,61639bc1f265eb00cf9687c8,615d58571c31b1006dc9525d,telemarketer,615d57831c31b1006dc95249,2023-10-04 06:08:49.721,651d0171bfc23d0007915621,pengalaman kerja menjadi agent telemarketer di...,25.0
1608,651d3ae3bfc23d00079159de,0,"JL.JOGOKARIYAN NO.43 A, RT 46 RW 12, MANTRIJER...",2023-10-04 10:13:55.952,1981-04-10,False,615e60a03c1e73007be5ccfc,Akuntansi,61639bc1f265eb00cf9687c8,615d586d1c31b1006dc95261,22 Agustus 2022,615d57461c31b1006dc9523d,2023-10-04 10:13:55.952,651d3ae3bfc23d00079159db,Pernah di gudang expedisi,42.0

In [8]:
# Assuming data_jobfair is a Pandas DataFrame with the 'usia_saat_melamar' column created previously

# Find the index of rows where 'usia_saat_melamar' is less than 15
index_to_drop = data_jobfair[data_jobfair['usia_saat_melamar'] < 15].index

# Drop the rows with the specified index
data_jobfair = data_jobfair.drop(index_to_drop)

Gender

In [9]:
gender_counts = data_jobfair['gender'].value_counts()
gender_counts

615e60a03c1e73007be5ccfc    798
615e60b53c1e73007be5cd01    796
-                             1
Name: gender, dtype: int64

In [10]:
for index, row in data_jobfair.iterrows():
    if row['gender'] == "615e60a03c1e73007be5ccfc":
        data_jobfair.loc[index, 'gender_baru'] = 'LAKI-LAKI'
    else :
        data_jobfair.loc[index, 'gender_baru'] = 'PEREMPUAN'

data_jobfair[['_id','gender_baru']]

                           _id gender_baru
0     6164d6a1c53d4900eb93ca7d   LAKI-LAKI
2     616e0a3f0b9434a8f783a9c6   LAKI-LAKI
3     61775332e8ae91003ce09423   LAKI-LAKI
4     61775d18e8ae91003ce09aec   LAKI-LAKI
5     61776c38e8ae91003ce0ab51   LAKI-LAKI
...                        ...         ...
1604  6505945b5554a70006e49c7c   LAKI-LAKI
1605  650db94bd3187e0007b02801   LAKI-LAKI
1606  65137138337a44000661ba61   LAKI-LAKI
1607  651d0171bfc23d0007915624   PEREMPUAN
1608  651d3ae3bfc23d00079159de   LAKI-LAKI

[1595 rows x 2 columns]

Pendidikan Terakhir

In [11]:
education_counts = data_jobfair['status_education'].value_counts()
education_counts

615d57831c31b1006dc95249    1017
615d57461c31b1006dc9523d     393
615d576f1c31b1006dc95245     149
615d57951c31b1006dc9524d      19
615d575c1c31b1006dc95241       8
615d56ee1c31b1006dc95225       4
-                              3
615d57311c31b1006dc95239       2
Name: status_education, dtype: int64

In [12]:
for index, row in data_jobfair.iterrows():
    if row['status_education'] == "615d581d1c31b1006dc95259":
        data_jobfair.loc[index, 'education'] = 'STRATA III'
    elif row['status_education'] == "615d57951c31b1006dc9524d":
        data_jobfair.loc[index, 'education'] = 'STRATA II'
    elif row['status_education'] == "615d57831c31b1006dc95249":
        data_jobfair.loc[index, 'education'] = 'DIPLOMA IV / STRATA 1'
    elif row['status_education'] == "615d576f1c31b1006dc95245":
        data_jobfair.loc[index, 'education'] = 'AKADEMI/DIPLOMA III/S. MUDA'
    elif row['status_education'] == "615d575c1c31b1006dc95241":
        data_jobfair.loc[index, 'education'] = 'DIPLOMA I/II'
    elif row['status_education'] == "615d57461c31b1006dc9523d":
        data_jobfair.loc[index, 'education'] = 'SLTA / SEDERAJAT'
    elif row['status_education'] == "615d57311c31b1006dc95239":
        data_jobfair.loc[index, 'education'] = 'SLTP / SEDERAJAT'
    elif row['status_education'] == "615d57161c31b1006dc9522d":
        data_jobfair.loc[index, 'education'] = 'TAMAT SD / SEDERAJAT'
    elif row['status_education'] == "615d57041c31b1006dc95229":
        data_jobfair.loc[index, 'education'] = 'TIDAK TAMAT SD / SEDERAJAT'
    else:
        data_jobfair.loc[index, 'education'] = 'TIDAK / BELUM SEKOLAH'

# Selecting relevant columns
result = data_jobfair[['_id', 'education']]

Marital Status

In [13]:
marital_status_counts = data_jobfair['marital_status'].value_counts()
marital_status_counts

61639bc1f265eb00cf9687c8    1289
61639bddf265eb00cf9687d1     305
-                              1
Name: marital_status, dtype: int64

In [14]:
for index, row in data_jobfair.iterrows():
    if row['marital_status'] == "61639bddf265eb00cf9687d1":
        data_jobfair.loc[index, 'Marital_Status'] = 'MENIKAH'
    else :
        data_jobfair.loc[index, 'Marital_Status'] = 'BELUM MENIKAH'

data_jobfair[['_id','Marital_Status']]

                           _id Marital_Status
0     6164d6a1c53d4900eb93ca7d        MENIKAH
2     616e0a3f0b9434a8f783a9c6  BELUM MENIKAH
3     61775332e8ae91003ce09423  BELUM MENIKAH
4     61775d18e8ae91003ce09aec        MENIKAH
5     61776c38e8ae91003ce0ab51        MENIKAH
...                        ...            ...
1604  6505945b5554a70006e49c7c  BELUM MENIKAH
1605  650db94bd3187e0007b02801  BELUM MENIKAH
1606  65137138337a44000661ba61  BELUM MENIKAH
1607  651d0171bfc23d0007915624  BELUM MENIKAH
1608  651d3ae3bfc23d00079159de  BELUM MENIKAH

[1595 rows x 2 columns]

Kondisi Fisik

In [15]:
physical_condition_counts = data_jobfair['physical_condition'].value_counts()
physical_condition_counts

615d586d1c31b1006dc95261    1582
615d58571c31b1006dc9525d      12
-                              1
Name: physical_condition, dtype: int64

In [16]:
for index, row in data_jobfair.iterrows():
    if row['physical_condition'] == "615d586d1c31b1006dc95261":
        data_jobfair.loc[index, 'Physical_Status'] = 'NON DISABILITAS'
    else :
        data_jobfair.loc[index, 'Physical_Status'] = 'DISABILITAS'

data_jobfair[['_id','Physical_Status']]

                           _id  Physical_Status
0     6164d6a1c53d4900eb93ca7d  NON DISABILITAS
2     616e0a3f0b9434a8f783a9c6  NON DISABILITAS
3     61775332e8ae91003ce09423  NON DISABILITAS
4     61775d18e8ae91003ce09aec  NON DISABILITAS
5     61776c38e8ae91003ce0ab51  NON DISABILITAS
...                        ...              ...
1604  6505945b5554a70006e49c7c  NON DISABILITAS
1605  650db94bd3187e0007b02801  NON DISABILITAS
1606  65137138337a44000661ba61  NON DISABILITAS
1607  651d0171bfc23d0007915624      DISABILITAS
1608  651d3ae3bfc23d00079159de  NON DISABILITAS

[1595 rows x 2 columns]

Profesi saat melamar kerja

In [17]:
profession_counts = data_jobfair['profession'].value_counts()
profession_counts

-                                                          81
Fresh Graduate                                             29
Mahasiswa                                                  24
Fresh graduate                                             23
Belum bekerja                                              17
                                                           ..
Freelancer UI/UX Designer                                   1
SMK                                                         1
Konsultan Badan Layanan Umum Daerah                         1
PT.  SAMPINGAN MITRA INDONESIA - ADMIN AGENT MONITORING     1
Testing Pencari Kerja ke 7                                  1
Name: profession, Length: 1147, dtype: int64

Asal daerah pelamar kerja (Contoh: Menggunakan kolom 'address' sebagai asal daerah)

In [18]:
location_counts = data_jobfair['address'].value_counts()
location_counts

GLAGAH UH 4/242, RT8, RW2, WARUNGBOTO, UMBULHARJO, KOTA YOGYAKARTA, DAERAH ISTIMEWA YOGYAKARTA                      2
NULISAN RT: 1 RW: 11 SUMBERAGUNG MOYUDAN...                                                                         2
TEMPEL NITIKAN UH 6 /227, RT 38 RW 10, SOROSUTAN, UMBULHARJO, KOTA YOGYAKARTA, DAERAH ISTIMEWA YOGYAKARTA           2
RT: 6 RW: 7 SUNGAI BAMBU TANJUNG PRIOK KOTA ADM. JAKARTA UTARA DKI JAKARTA                                          2
DK. IV CUNGKUK RT: 2 RW:  NGESTIHARJO KASIHAN BANTUL DAERAH ISTIMEWA YOGYAKARTA                                     2
                                                                                                                   ..
RT: 1 RW: 2 KEMIRI KIDUL KEMIRI...                                                                                  1
KEMETIRAN KIDUL GT II/21, RT 55 RW 16, PRINGGOKUSUMAN, GEDONGTENGEN, KOTA YOGYAKARTA, DAERAH ISTIMEWA YOGYAKARTA    1
Kerto RT 001 Pleret Pleret Bantul                                                                                   1
JL.KRESNO WB.2/11 YKA., RT40, RW9, WIROBRAJAN, WIROBRAJAN, KOTA YOGYAKARTA, DAERAH ISTIMEWA YOGYAKARTA              1
NGUJUNG DK. IV RT: 2 RW: 0 GADINGHARJO SANDEN BANTUL DAERAH ISTIMEWA YOGYAKARTA                                     1
Name: address, Length: 1580, dtype: int64

Pengalaman kerja

In [19]:
work_experience_counts = data_jobfair['work_experience'].value_counts()
work_experience_counts

-                                                                                                                                                                                                                                                                                                         62
Fresh graduate                                                                                                                                                                                                                                                                                            19
Belum ada                                                                                                                                                                                                                                                                                                 18
Fresh Graduate                                                                                                                                                                                                                                                                                            14
Belum bekerja                                                                                                                                                                                                                                                                                              7
                                                                                                                                                                                                                                                                                                          ..
Accounting Staff di PT Rumah Flora Fauna, 2019-2020\nInternal Audit Staff di PT Sri Rejeki Isman Tbk, 2018-2019                                                                                                                                                                                            1
1. Tahun 2014 Selama 3 bulan ( Magang) di Fakultas Hukum, UGM \n2. Tahun 2015 Selama 5 bulan di Obralan Baju dan Sprei sebagai Admin \n3. Tahun 2019 Selama 1 tahun 10 bulan di Roocket Media sebagai Administrasi\n4. Tahun 2021 Selama 3 bulan di PT. Lantabura Media Sebagai Admin Customer Service     1
Belum Ada                                                                                                                                                                                                                                                                                                  1
Saya pernah menjadi Content Writer selama 1 tahun (Mei 2019-Mei 2020) di PT. Sendok Sumpit Group dan kemudian menjadi Staf Admin selama kurang dari 1 tahun (Mei 2020 - Maret 2021) di Law Office ARM & Partners                                                                                           1
Menjual makanan ringan                                                                                                                                                                                                                                                                                     1
Name: work_experience, Length: 1439, dtype: int64

Jurusan pelamar kerja

In [20]:
major_counts = data_jobfair['major'].value_counts()
major_counts

Akuntansi                       158
Manajemen                        85
IPA                              36
Teknik Informatika               36
Psikologi                        35
                               ...
Electrical engineering            1
Farmasi - Profesi Apoteker        1
TEKNOLOGI INDUSTRI PERTANIAN      1
BIOLOGI                           1
S1 Kimia                          1
Name: major, Length: 579, dtype: int64

In [21]:
data_jobfair.isna().sum()

_id                   0
__v                   0
address               0
createdAt             0
date_of_birth         0
deleted               0
gender                0
major                 0
marital_status        0
physical_condition    0
profession            0
status_education      0
updatedAt             0
user_id               0
work_experience       0
usia_saat_melamar     0
gender_baru           0
education             0
Marital_Status        0
Physical_Status       0
dtype: int64

Menyimpan hasil analisis ke dalam file Excel

In [22]:
proporsi_data = pd.DataFrame({
    'Usia saat Melamar Kerja': data_jobfair['usia_saat_melamar'],
    'Gender': data_jobfair['gender_baru'],
    'Pendidikan Terakhir': data_jobfair['education'],
    'Marital Status': data_jobfair['Marital_Status'],
    'Kondisi Fisik': data_jobfair['Physical_Status'],
    'Profesi saat Melamar Kerja': data_jobfair['profession'],
    'Asal Daerah Pelamar Kerja': data_jobfair['address'],
    'Pengalaman Kerja': data_jobfair['work_experience'],
    'Jurusan Pelamar Kerja': data_jobfair['major']
})
proporsi_data.to_excel('proporsi_data.xlsx', index=False)

hasil analisis

In [23]:
print("Analisis proporsi data pencari kerja:")
print("\na. Usia saat melamar kerja:")
print(data_jobfair[['user_id', 'usia_saat_melamar']])
print("\nb. Gender:")
print(gender_counts)
print("\nc. Pendidikan Terakhir:")
print(education_counts)
print("\nd. Marital Status:")
print(marital_status_counts)
print("\ne. Kondisi Fisik:")
print(physical_condition_counts)
print("\nf. Profesi saat melamar kerja:")
print(profession_counts)
print("\ng. Asal daerah pelamar kerja:")
print(location_counts)
print("\nh. Pengalaman kerja:")
print(work_experience_counts)
print("\ni. Jurusan pelamar kerja:")
print(major_counts)

print("\nHasil analisis telah disimpan dalam file 'proporsi_data.xlsx'.")

Analisis proporsi data pencari kerja:

a. Usia saat melamar kerja:
                       user_id  usia_saat_melamar
0     6164d6a0c53d4900eb93ca79               33.0
2     616e0a3f0b9434a8f783a9c2               25.0
3     61775328125736004cceb9cb               22.0
4     61775d1817c4e8004c70e2f4               40.0
5     61776c38804d6b0068e60d44               33.0
...                        ...                ...
1604  6505945a5554a70006e49c79               25.0
1605  650db94bd3187e0007b027fe               35.0
1606  65137138337a44000661ba5e               25.0
1607  651d0171bfc23d0007915621               25.0
1608  651d3ae3bfc23d00079159db               42.0

[1595 rows x 2 columns]

b. Gender:
615e60a03c1e73007be5ccfc    798
615e60b53c1e73007be5cd01    796
-                             1
Name: gender, dtype: int64

c. Pendidikan Terakhir:
615d57831c31b1006dc95249    1017
615d57461c31b1006dc9523d     393
615d576f1c31b1006dc95245     149
615d57951c31b1006dc9524d      19
615d575c1c31b1006dc95241       8
615d56ee1c31b1006dc95225       4
-                              3
615d57311c31b1006dc95239       2
Name: status_education, dtype: int64

d. Marital Status:
61639bc1f265eb00cf9687c8    1289
61639bddf265eb00cf9687d1     305
-                              1
Name: marital_status, dtype: int64

e. Kondisi Fisik:
615d586d1c31b1006dc95261    1582
615d58571c31b1006dc9525d      12
-                              1
Name: physical_condition, dtype: int64

f. Profesi saat melamar kerja:
-                                                          81
Fresh Graduate                                             29
Mahasiswa                                                  24
Fresh graduate                                             23
Belum bekerja                                              17
                                                           ..
Freelancer UI/UX Designer                                   1
SMK                                                         1
Konsultan Badan Layanan Umum Daerah                         1
PT.  SAMPINGAN MITRA INDONESIA - ADMIN AGENT MONITORING     1
Testing Pencari Kerja ke 7                                  1
Name: profession, Length: 1147, dtype: int64

g. Asal daerah pelamar kerja:
GLAGAH UH 4/242, RT8, RW2, WARUNGBOTO, UMBULHARJO, KOTA YOGYAKARTA, DAERAH ISTIMEWA YOGYAKARTA                      2
NULISAN RT: 1 RW: 11 SUMBERAGUNG MOYUDAN...                                                                         2
TEMPEL NITIKAN UH 6 /227, RT 38 RW 10, SOROSUTAN, UMBULHARJO, KOTA YOGYAKARTA, DAERAH ISTIMEWA YOGYAKARTA           2
RT: 6 RW: 7 SUNGAI BAMBU TANJUNG PRIOK KOTA ADM. JAKARTA UTARA DKI JAKARTA                                          2
DK. IV CUNGKUK RT: 2 RW:  NGESTIHARJO KASIHAN BANTUL DAERAH ISTIMEWA YOGYAKARTA                                     2
                                                                                                                   ..
RT: 1 RW: 2 KEMIRI KIDUL KEMIRI...                                                                                  1
KEMETIRAN KIDUL GT II/21, RT 55 RW 16, PRINGGOKUSUMAN, GEDONGTENGEN, KOTA YOGYAKARTA, DAERAH ISTIMEWA YOGYAKARTA    1
Kerto RT 001 Pleret Pleret Bantul                                                                                   1
JL.KRESNO WB.2/11 YKA., RT40, RW9, WIROBRAJAN, WIROBRAJAN, KOTA YOGYAKARTA, DAERAH ISTIMEWA YOGYAKARTA              1
NGUJUNG DK. IV RT: 2 RW: 0 GADINGHARJO SANDEN BANTUL DAERAH ISTIMEWA YOGYAKARTA                                     1
Name: address, Length: 1580, dtype: int64

h. Pengalaman kerja:
-                                                                                                                                                                                                                                                                                                         62
Fresh graduate                                                                                                                                                                                                                                                                                            19
Belum ada                                                                                                                                                                                                                                                                                                 18
Fresh Graduate                                                                                                                                                                                                                                                                                            14
Belum bekerja                                                                                                                                                                                                                                                                                              7
                                                                                                                                                                                                                                                                                                          ..
Accounting Staff di PT Rumah Flora Fauna, 2019-2020\nInternal Audit Staff di PT Sri Rejeki Isman Tbk, 2018-2019                                                                                                                                                                                            1
1. Tahun 2014 Selama 3 bulan ( Magang) di Fakultas Hukum, UGM \n2. Tahun 2015 Selama 5 bulan di Obralan Baju dan Sprei sebagai Admin \n3. Tahun 2019 Selama 1 tahun 10 bulan di Roocket Media sebagai Administrasi\n4. Tahun 2021 Selama 3 bulan di PT. Lantabura Media Sebagai Admin Customer Service     1
Belum Ada                                                                                                                                                                                                                                                                                                  1
Saya pernah menjadi Content Writer selama 1 tahun (Mei 2019-Mei 2020) di PT. Sendok Sumpit Group dan kemudian menjadi Staf Admin selama kurang dari 1 tahun (Mei 2020 - Maret 2021) di Law Office ARM & Partners                                                                                           1
Menjual makanan ringan                                                                                                                                                                                                                                                                                     1
Name: work_experience, Length: 1439, dtype: int64

i. Jurusan pelamar kerja:
Akuntansi                       158
Manajemen                        85
IPA                              36
Teknik Informatika               36
Psikologi                        35
                               ...
Electrical engineering            1
Farmasi - Profesi Apoteker        1
TEKNOLOGI INDUSTRI PERTANIAN      1
BIOLOGI                           1
S1 Kimia                          1
Name: major, Length: 579, dtype: int64

Hasil analisis telah disimpan dalam file 'proporsi_data.xlsx'.